config/routes.rb
Rails.application.routes.draw do
  get 'sales/new'
  get 'sales/done'
  post 'sales/create'
  resources :sales
  root 'sales#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
    # validates :code, uniqueness: true
    validates :detail, presence: true
    validates :category, inclusion: {in: [1,2,3,4,5]}
    validates :value, numericality: true
    validates :discount, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 40}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  
  def new
  end

  def create
    sale = Sale.new
    sale.detail = params[:sale][:detail]
    sale.value = params[:sale][:value]
    sale.category = params[:sale][:category]
    sale.total = params[:sale][:value].to_f * (1-params[:sale][:discount].to_f/100)
    sale.discount = params[:sale][:discount]
    if params[:sale][:tax]!=1
      sale.total = sale.total * 1.19
      sale.tax = 19
    end
    if sale.save
      redirect_to sales_done_path
    end
  end
  
  def done 
      @last_sale = Sale.last 
  end

  private
    
    def sale_params
      params.require(:sale).permit(:detail, :value, :category, :discount, :tax)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalesRecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/cerulean/bootstrap.min.css" rel="stylesheet" integrity="sha384-C++cugH8+Uf86JbNOnQoBweHHAe/wVKN/mb0lTybu/NZ9sEYbd+BbbYtNpWYAsNP" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </div>
  </body>
</html>

app/views/sales/done.html.erb
<h1> "El registro fue almacenado con éxito!" </h1>
<br>


<table class= 'table'>
<tr>
    <td><strong>Detalle</strong>  </td>
    <td><strong>Categoria</strong>  </td>
    <td><strong>Monto</strong>  </td>
    <td><strong>Descuento</strong>  </td>
</tr>

<tr>
    <td><%= @last_sale.detail %></td>
    <td><%= @last_sale.category %></td>
    <td><%= @last_sale.value %></td>
    <td><%= @last_sale.discount %></td>
</tr>
</table>


<button type="button" class="btn btn-primary btn-light"><%= link_to 'Volver', new_sale_path %></button>

app/views/sales/new.html.erb
<h1>Ventas</h1>



<%= form_with model: Sale.new, local: true do |f| %>
<div class="form-group">
<%= f.label :detail, 'Detalle' %>
<%= f.text_area :detail, class:'form-control' %>
</div>
<div class="form-group">
<%= f.label :detail, 'Categoria' %>
<%= f.number_field :category, class:'form-control' %>
</div>
<div class="form-group">
<%= f.label :detail, 'Monto' %>
<%= f.number_field :value, class:'form-control' %>
</div>
<div class="form-group">
<%= f.label :detail, 'Descuento' %>
<%= f.number_field :discount, class:'form-control' %>
</div>
<div class="form-group">
<%= f.check_box :tax %> <%= f.label :tax, 'Exento de iva' %>
</div>
<%= f.submit 'Crear' %>




<% end %>